brew install autoconf
brew install automake
brew install bash-completion
brew install cairo
brew install coreutils
brew install findutils
brew install fontconfig
brew install freetype
brew install gcc
brew install gdbm
brew install gettext
brew install glib
brew install gmp
brew install gnu-sed
brew install gnu-which
brew install gnutls
brew install go
brew install grep
brew install isl
brew install jpeg
brew install libffi
brew install libmpc
brew install libpng
brew install libtasn1
brew install libtiff
brew install libtool
brew install libunistring
brew install libyaml
brew install makedepend
brew install mobile-shell
brew install mpfr
brew install nettle
brew install openssl
brew install openssl@1.1
brew install p11-kit
brew install pcre
brew install perl
brew install pixman
brew install pkg-config
brew install protobuf
brew install python
brew install r
brew install readline
brew install ruby
brew install screen
brew install sqlite
brew install texinfo
brew install tree
brew install wget
brew install xz
brew install youtube-dl
